#!/usr/bin/env python3
"""Fig. 3 (Ch. 3, route generation): example routes per difficulty level.

Draws, for each training level (easy/medium/hard = 30/60/100 m), a top-down
Town03 panel with the road topology as backdrop and a few example routes
generated by the PRODUCTION planner (`carla_core.envs.route_planner.
CARLARoutePlanner`): vehicle routes (GRP, solid) and pedestrian sidewalk
chains with max_cross=3 (dashed).

MEASUREMENT ONLY — no env/planner change. Requires a LIVE CARLA 0.9.16
server; the user runs it (never Claude), with the training Python env so
that `carla` and `carla_core` are importable:

    python docs/thesis/scripts/make_fig3_route_examples.py [--host 127.0.0.1]
        [--port 2000] [--no-reload] [--n 3] [--seed 999]

`--no-reload` skips client.load_world (use if Town03 is already loaded —
load_world RESETS the world, do not aim it at a sim you need intact).
Output: docs/thesis/latex/figures/route_examples.pdf
STATUS: written 2026-07-14, NOT yet executed (needs live server).
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np

REPO = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(REPO))

try:
    import carla
except ImportError as exc:
    sys.stderr.write(
        "ERROR: cannot import 'carla'. Run with the training Python env.\n"
    )
    raise SystemExit(2) from exc

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt

from carla_core.envs.route_planner import CARLARoutePlanner

LEVELS = [("easy", 30.0), ("medium", 60.0), ("hard", 100.0)]
OUT = REPO / "docs/thesis/latex/figures/route_examples.pdf"


def wp_xy(wps):
    return (
        [w.transform.location.x for w in wps],
        [w.transform.location.y for w in wps],
    )


def draw_backdrop(ax, cmap):
    """Light-gray road topology as spatial context."""
    for wp_a, wp_b in cmap.get_topology():
        a, b = wp_a.transform.location, wp_b.transform.location
        ax.plot([a.x, b.x], [a.y, b.y], color="0.85", linewidth=0.6, zorder=1)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--host", default="127.0.0.1")
    ap.add_argument("--port", type=int, default=2000)
    ap.add_argument("--town", default="Town03")
    ap.add_argument("--no-reload", action="store_true")
    ap.add_argument("--n", type=int, default=3, help="routes per class per level")
    ap.add_argument("--seed", type=int, default=999)
    args = ap.parse_args()

    client = carla.Client(args.host, args.port)
    client.set_timeout(60.0)
    world = client.get_world() if args.no_reload else client.load_world(args.town)
    cmap = world.get_map()
    spawn_points = cmap.get_spawn_points()
    planner = CARLARoutePlanner(cmap)

    fig, axes = plt.subplots(1, len(LEVELS), figsize=(12.5, 4.4), sharex=True, sharey=True)
    veh_colors = ["tab:blue", "tab:cyan", "steelblue"]
    ped_colors = ["tab:red", "tab:orange", "firebrick"]

    for ax, (level, target) in zip(axes, LEVELS):
        draw_backdrop(ax, cmap)
        n_veh = n_ped = 0
        attempt = 0
        # Vehicle examples: origins drawn deterministically from spawn points.
        while n_veh < args.n and attempt < args.n * 10:
            rng = np.random.default_rng(
                np.random.SeedSequence([args.seed, int(target), attempt])
            )
            origin = spawn_points[int(rng.integers(len(spawn_points)))].location
            wps = planner.plan_vehicle_route(origin, target, spawn_points, rng=rng)
            attempt += 1
            if not wps:
                continue
            xs, ys = wp_xy(wps)
            ax.plot(xs, ys, "-", color=veh_colors[n_veh % 3], linewidth=1.6, zorder=3)
            ax.plot(xs[0], ys[0], "o", color=veh_colors[n_veh % 3], markersize=3.5, zorder=4)
            n_veh += 1
        # Pedestrian examples: origins from the navigation mesh (as in the env).
        attempt = 0
        while n_ped < args.n and attempt < args.n * 20:
            loc = world.get_random_location_from_navigation()
            attempt += 1
            if loc is None:
                continue
            wps, n_cross = planner.plan_pedestrian_route_by_distance(
                loc, target, return_meta=True
            )
            if not wps:
                continue
            xs, ys = wp_xy(wps)
            ax.plot(xs, ys, "--", color=ped_colors[n_ped % 3], linewidth=1.4, zorder=3)
            ax.plot(xs[0], ys[0], "s", color=ped_colors[n_ped % 3], markersize=3.5, zorder=4)
            n_ped += 1
            print(f"[{level}] ped route: {len(wps)} wps, {n_cross} crossings")
        ax.set_title(f"{level} ({target:.0f} m)", fontsize=10)
        ax.set_aspect("equal")
        ax.set_xticks([])
        ax.set_yticks([])
        print(f"[{level}] drew {n_veh} vehicle + {n_ped} pedestrian routes")

    fig.suptitle(
        "Example routes per level — vehicles (solid, GRP) and pedestrians "
        "(dashed, sidewalk chains, max 3 crossings)", fontsize=10)
    fig.tight_layout()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(OUT, bbox_inches="tight")
    print(f"written: {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
